<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="JAJ.Packages.MiniAudioEx" Version="3.3.6" />
    <PackageReference Include="SDL3-CS" Version="3.4.2" />
    <PackageReference Include="SDL3-CS.Native" Version="3.4.2" />
    <PackageReference Include="SDL3-CS.Native.Image" Version="3.5.0" />
    <PackageReference Include="SDL3-CS.Native.Mixer" Version="3.2.0" />
    <PackageReference Include="SDL3-CS.Native.Shadercross" Version="3.0.0" />
    <PackageReference Include="SDL3-CS.Native.TTF" Version="3.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Prion\Prion.csproj" />
    <ProjectReference Include="..\ErisMath\ErisMath.csproj" />
  </ItemGroup>
</Project>
